# Request(== Goal) (robot_task_client -> robot_task_server)
string robot_name
string goal_location
---
# Response(robot_task_server -> robot_task_client)
string result_msg
---
# Feedback(robot_task_server -> robot_task_client)
float32 remaining_distance 
