string product_code
string task_type
---
string robot_name
string goal_location
string task_assignment


##변경예정
# string task_code
# string[] product_code_list  // ['P02', 'P01', 'P03']
# string task_type
#---
# string robot_name  // "Robo1"
# string task_code  // "Task_2"
# string[] rack_list  // ["R_A1", "R_B2", "R_C3"]
# string task_assignment  // "입고"

